version: 2.1

orbs:  
  python: circleci/python@0.3.2
  aws-cli: circleci/aws-cli@1.2.1

jobs:  
  build:
    executor:
      name: python/default
      tag: '3.9'
    steps:
      - checkout
      - run:
          name: Setup Virtual env
          command: |
            virtualenv -p python3.9 env
            echo "source ./env/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt   

workflows:  
  build-and-deploy:    
    jobs:      
      - build:
          context: matching-engine-api
          filters:            
            branches:
              only:
                - qa
      - deploy-dev:
          context: matching-engine-api
          requires:
            - build
          filters:        
            branches:
              only:
                - qa